name: Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "ASSUMPTIONS.md"
      - ".env.example"
      - "pnpm-workspace.yaml"

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: naqqosh/zehngoh-ui/.github/workflows/docker-build-deploy.yml@main

    with:
      image_name: ${{ vars.USER_API_IMAGE_NAME }}

    secrets: inherit
